#================================
# Robo Miep
#================================ 

  #=====================
  # Map
  #=====================

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: "de"
    name: "Robomiep Camera"
    draw: ['all']
    attributes:
      - calibration_points
      - charger
      - cleaned_rooms
      - country
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - ignored_obstacles
      - obstacles_with_photo
      - ignored_obstacles_with_photo
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - vacuum_room_name
      - walls
      - zones
    colors:
      color_map_inside: [0, 0, 0, 0]
      color_map_outside: [0, 0, 0, 0]
      color_unknown: [0, 0, 0, 0]
      color_robo: [235, 235, 235]
      color_path: [255, 255, 255]
      color_charger: [201, 204, 173]
      color_room_names: [255, 255, 255]
      color_cleaned_area: [140, 140, 140]
    room_colors:
      16: [252, 186, 3]
      17: [10, 182, 194]
      18: [34, 150, 227]
      19: [191, 107, 88]
      20: [165, 114, 181]
    map_transformation:
      scale: 2
    sizes:
      charger_radius: 6.5
      vacuum_radius: 8
    scan_interval:
      seconds: 5
    auto_update: true
    


  #=====================
  # Automations
  #=====================
automation:

    #=====================
    # Stofzuig Keuken En Woonkamer
    #=====================
  - alias: "Vacuum kitchen and living"
    trigger:
    - platform: time
      at: '19:15:00'
    condition: []
    action:
    - service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: [17,18]

  #=====================
  # Scripts
  #=====================
script:

    #=====================
    # Stofzuig Woonkamer
    #=====================
  vacuum_living:
    alias: "Vacuum Living"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 18

    #=====================
    # Stofzuig Hal
    #=====================
  vacuum_hall:
    alias: "Vacuum Hall"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 16 

    #=====================
    # Stofzuig Keuken
    #=====================
  vacuum_kitchen:
    alias: "Vacuum Kitchen"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 17

    #=====================
    # Stofzuig Keuken en Woonkamer
    #=====================
  vacuum_kitchen_living:
    alias: "Vacuum Kitchen and Living"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: [17,18]

    #=====================
    # Stofzuig Overloop
    #=====================
  vacuum_overloop:
    alias: "Vacuum Overloop"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 18

    #=====================
    # Stofzuig Kamer Fynn
    #=====================
  vacuum_fynn:
    alias: "Vacuum Kamer Fynn"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 20 

    #=====================
    # Stofzuig Kamer Luca
    #=====================
  vacuum_luca:
    alias: "Vacuum Kamer Luca"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 19

    #=====================
    # Stofzuig Kamer Sab en Dunc
    #=====================
  vacuum_sleep:
    alias: "Vacuum Kamer Sab en Dunc"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 16

    #=====================
    # Stofzuig Badkamer
    #=====================
  vacuum_bathroom:
    alias: "Vacuum Badkamer"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: 17

    #=====================
    # Stofzuig Verdieping
    #=====================
  vacuum_floor1:
    alias: "Vacuum Verdieping"
    sequence:
      service: xiaomi_miio.vacuum_clean_segment
      target:
        entity_id: vacuum.miep
      data:
        segments: [16,18,19,20]