# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
logbook:
    include: !include includes/recorder_include.yaml

history:
    include: !include includes/recorder_include.yaml

recorder:
    db_url: !secret maria_db_url
    purge_keep_days: 30
    commit_interval: 900
    auto_purge: true
    include: !include includes/recorder_include.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem
    use_x_forwarded_for: true
    trusted_proxies:
      - 192.168.2.207

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-bha-icons/hass-bha-icons.js

browser_mod:
  prefix: "browser_mod_"

#================================  
# Customize UI
#================================
homeassistant:
  packages: !include_dir_named packages
  customize: !include includes/customize.yaml
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
      
#================================  
# Text to speech
#================================
tts:
  - platform: google_translate

#================================
# Redirects
#================================
group: !include includes/groups.yaml
automation: !include includes/automations.yaml
scene: !include includes/scenes.yaml
sensor: !include includes/sensors.yaml
input_number: !include includes/input_numbers.yaml
proximity: !include includes/proximity.yaml
light: !include includes/lights.yaml
notify: !include includes/notify.yaml
binary_sensor: !include  includes/binary_sensors.yaml
input_boolean: !include  includes/input_booleans.yaml