#================================
# Bloom-Data
#================================

  #===============
  # Sensors
  #===============

sensor:

    #================================  
    # Certificates
    #================================

  - platform: template
    sensors:
        cert_expiry_days_bloom_data:
            friendly_name: Certificate Expiry Bloom-Data
            value_template: >-
                {% set expiration_date = (as_timestamp(states.sensor.cert_expiry_timestamp_bloom_data_synology_me.state) | int) %}
                {% set todays_date = (now().strftime("%s") | int ) %}
                {% if todays_date > expiration_date %}
                  {% set countdown = "Expired" %}
                {% else %}
                  {% set countdown = ((expiration_date - todays_date | int) / 24 / 60 / 60) | round(0) %}
                {% endif %}
                {{countdown}}
            entity_picture_template: >-
                {% if states('sensor.cert_expiry_days_bloom_data')|float > 10 %}
                  /local/Custom_Icons/certificate-ok-ico.png
                {% else %}
                  /local/Custom_Icons/certificate-nok-ico.png
                {% endif %}
            unit_of_measurement: 'days'

    #================================
    # Security
    #================================

  - platform: template
    sensors:
      bloom_data_security:
        value_template: >-
          {% if is_state('binary_sensor.bloom_data_security_status', 'off') %}
            Safe
          {% else %}
            Unsafe
          {% endif %}
          
  - platform: template
    sensors:
        bloom_data_update:
            value_template: >-
                {% if is_state('update.bloom_data_dsm_update', 'off') %}
                    Up-To-Date
                {% else %}
                    Needs Update
                {% endif %}

  - platform: template
    sensors:
      bloom_data_safety:
        value_template: >-
          {% if is_state('binary_sensor.bloom_data_security_status', 'on') %}
            Unsafe
          {% elif not is_state('sensor.bloom_data_volume_1_status', 'normal') %}
            Unsafe
          {% else %}
            Safe
          {% endif %}

    #================================
    # Disk 1
    #================================

  - platform: template
    sensors:
        bloom_data_disk_1_age:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_1_below_min_remaining_life', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
        bloom_data_disk_1_sectors:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_1_exceeded_max_bad_sectors', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
      bloom_data_safety_disk_1:
        value_template: >-
          {% if is_state('binary_sensor.bloom_data_drive_1_below_min_remaining_life', 'on') %}
            Unsafe
          {% elif is_state('binary_sensor.bloom_data_drive_1_exceeded_max_bad_sectors', 'on') %}
            Unsafe
          {% elif not is_state('sensor.bloom_data_drive_1_status', 'normal') %}
            Unsafe
          {% else %}
            Safe
          {% endif %}

    #================================
    # Disk 2
    #================================

  - platform: template
    sensors:
        bloom_data_disk_2_age:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_2_below_min_remaining_life', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
        bloom_data_disk_2_sectors:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_2_exceeded_max_bad_sectors', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
      bloom_data_safety_disk_2:
        value_template: >-
          {% if is_state('binary_sensor.bloom_data_drive_2_below_min_remaining_life', 'on') %}
            Unsafe
          {% elif is_state('binary_sensor.bloom_data_drive_2_exceeded_max_bad_sectors', 'on') %}
            Unsafe
          {% elif not is_state('sensor.bloom_data_drive_2_status', 'normal') %}
            Unsafe
          {% else %}
            Safe
          {% endif %}

    #================================
    # Disk 3
    #================================

  - platform: template
    sensors:
        bloom_data_disk_3_age:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_3_below_min_remaining_life', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
        bloom_data_disk_3_sectors:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_3_exceeded_max_bad_sectors', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
      bloom_data_safety_disk_3:
        value_template: >-
          {% if is_state('binary_sensor.bloom_data_drive_3_below_min_remaining_life', 'on') %}
            Unsafe
          {% elif is_state('binary_sensor.bloom_data_drive_3_exceeded_max_bad_sectors', 'on') %}
            Unsafe
          {% elif not is_state('sensor.bloom_data_drive_3_status', 'normal') %}
            Unsafe
          {% else %}
            Safe
          {% endif %}

    #================================
    # Disk 4
    #================================

  - platform: template
    sensors:
        bloom_data_disk_4_age:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_4_below_min_remaining_life', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
        bloom_data_disk_4_sectors:
            value_template: >-
                {% if is_state('binary_sensor.bloom_data_drive_4_exceeded_max_bad_sectors', 'off') %}
                    Safe
                {% else %}
                    Unsafe
                {% endif %}

  - platform: template
    sensors:
      bloom_data_safety_disk_4:
        value_template: >-
          {% if is_state('binary_sensor.bloom_data_drive_4_below_min_remaining_life', 'on') %}
            Unsafe
          {% elif is_state('binary_sensor.bloom_data_drive_4_exceeded_max_bad_sectors', 'on') %}
            Unsafe
          {% elif not is_state('sensor.bloom_data_drive_4_status', 'normal') %}
            Unsafe
          {% else %}
            Safe
          {% endif %}

    #================================
    # Uptime
    #================================   
  - platform: template
    sensors:
      bloomdata_uptime:
        friendly_name: Bloom-Data Uptime
        value_template: >
          {% set up_time = as_timestamp(now()) - as_timestamp(states('sensor.bloom_data_last_boot')) %}

          {% set minutes = (up_time // 60) | int %}
          {% set hours = (minutes // 60) %}
          {% set days = (hours // 24) %}
          {% set weeks = (days // 7) %}

          {% set minutes = (minutes % 60) %}
          {% set hours =  (hours % 24) %}
          {% set days = (days % 7) %}

          {% macro phrase(value, name) %}
                    {%- set value = value %}
                    {%- set end = 's' if value > 1 else '' %}
                    {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
          {%- endmacro %}
                    
          {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
          {% set last_comma = text.rfind(',') %}
          {% if last_comma != -1 %}
            {% set text = text[:last_comma] + ' and' + text[last_comma + 1:] %}
          {% endif %}
          
          {{ text }}

    #================================
    # Firmware
    #================================  

  - platform: template
    sensors:
      synology_os:
          friendly_name: "Synology OS"
          value_template: "{{ 'Synology DSM' }}"

      bloom_data_hardware:
          friendly_name: "Bloom-Data Hardware"
          value_template: "{{ 'DiskStation DS 920+' }}"

      bloom_data_installed_firmware:
          friendly_name: "Bloom-Data Installed Firmware"
          value_template: "{{state_attr('update.bloom_data_dsm_update', 'installed_version')}}"

      bloom_data_latest_firmware:
          friendly_name: "Bloom-Data Latest Firmware"
          value_template: "{{state_attr('update.bloom_data_dsm_update', 'latest_version')}}"

      bloom_data_average_disk_temp:
          friendly_name: "Bloom-Data Average Disk Temperature"
          value_template: > 
            {{ ((float(states('sensor.bloom_data_drive_1_temperature')) +
                 float(states('sensor.bloom_data_drive_2_temperature')) +
                 float(states('sensor.bloom_data_drive_3_temperature')) +
                 float(states('sensor.bloom_data_drive_4_temperature'))) / 4) | round(2)
            }}