trigger:
  name: Trigger a Node-RED Node
  description: >
    Trigger a Node-RED node.
  target:
    entity:
      integration: nodered
      domain: switch
  fields:
    output_path:
      default: "0"
      description: Comma separated list of paths to send the message to. Zero is used to send the message to all paths.
      example: "1,2"
      selector:
        text:
    message:
      description: The message object that will be sent to the next node.
      selector:
        object:
