#================================
# Nginx
#================================

  #===============
  # Sensors
  #===============

sensor:

    #================================  
    # Certificates
    #================================

  - platform: template
    sensors:
        cert_expiry_days_bloomlannl:
            friendly_name: Certificate Expiry bloomlan.nl
            value_template: >-
                {% set expiration_date = (as_timestamp(states.sensor.cert_expiry_timestamp_bloomlan_nl.state) | int) %}
                {% set todays_date = (now().strftime("%s") | int ) %}
                {% if todays_date > expiration_date %}
                  {% set countdown = "Expired" %}
                {% else %}
                  {% set countdown = ((expiration_date - todays_date | int) / 24 / 60 / 60) | round(0) %}
                {% endif %}
                {{countdown}}
            entity_picture_template: >-
                {% if states('sensor.cert_expiry_days_bloomlannl')|float > 10 %}
                  /local/Custom_Icons/certificate-ok-ico.png
                {% else %}
                  /local/Custom_Icons/certificate-nok-ico.png
                {% endif %}
            unit_of_measurement: 'days'

        nginx_os:
            friendly_name: NGINX OS
            value_template: "{{ state_attr('sensor.rpi_monitor_nginx', 'ux_release') }} {{ state_attr('sensor.rpi_monitor_nginx', 'ux_version') }}"

        nginx_model:
            friendly_name: NGINX Model
            value_template: "{{ state_attr('sensor.rpi_monitor_nginx', 'rpi_model') }}"

        nginx_ram_usage:
            friendly_name: NGINX RAM usage
            unit_of_measurement: '%'
            value_template: "{{ (((state_attr('sensor.rpi_monitor_nginx', 'memory').size_mb | float) - (state_attr('sensor.rpi_monitor_nginx', 'memory').free_mb | float)) / (state_attr('sensor.rpi_monitor_nginx', 'memory').size_mb | float ) * 100) | round(0) }}"

        nginx_last_update:
            friendly_name: NGINX Last Update
            value_template: >
              {% set last_update = (as_timestamp(state_attr('sensor.rpi_monitor_nginx', 'last_update'))) %}
              {{ last_update | timestamp_custom('%d-%m-%Y')}}

        nginx_uptime:
            friendly_name: NGINX Uptime
            value_template: "{{ state_attr('sensor.rpi_monitor_nginx', 'up_time') }}"

        nginx_ip:
            friendly_name: NGINX IP
            value_template: "{{ state_attr('sensor.rpi_monitor_nginx', 'networking').eth0.IP }}"