#================================
# Monitor Docker
#================================ 

monitor_docker:
  - name: Docker
    url: !secret monitor_docker_url
    containers:
      - Bazarr
      - Jackett
      - HARepository
      - Mosquitto
      - NodeRed
      - phpMyAdmin
      - Plex
      - Portainer
      - Radarr
      - TasmoAdmin
      - Deluge
      - Unifi_Controller
      - watchtower
      - Wordpress
      - Zigbee2MQTT
      - ZwaveJS2MQTT
      - DockerProxy
      - ESPHome
      - WordpressDB
      - HA_InfluxDB
      - Grafana
    rename:
      Torrents: Deluge
      Unifi_Controller: Unifi Controller
      zwavejs2mqtt: ZwaveJS2MQTT
      DockerProxy: Docker Proxy
      HA_InfluxDB: HA InfluxDB
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - state
      - status
      - containers_memory_percentage
      - containers_1cpu_percentage

  #================================
  # Sensors
  #================================

sensor:
  - platform: template
    sensors:    
      docker_kernel:
          friendly_name: "Docker Kernel"
          value_template: "{{state_attr('sensor.docker_version', 'Kernel')}}"