#================================
# Github
#================================ 

  #================================
  # Sensors
  #================================ 

sensor:
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'dbloom86/HomeAssistant'
        name: Home Assistant
      - path: 'dbloom86/zigbee2mqtt.io'
        name: Zigbee2MQTT