#================================
# Toon climate
#================================

climate:

  - platform: toon_climate
    name: TOON Thermostat
    host: !secret toon_ip
    port: !secret toon_poort
    scan_interval: 60

  #===============
  # Automations
  #===============

automation:

  - alias: Set Climate to Vacation when away for more than a day
    trigger:
    - platform: state
      entity_id: group.ouders
      to: not_home
      for: 
        hours: 24
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.toon_thermostat
        attribute: preset_modes
        state: eco
    action:
      - service: climate.set_preset_mode
        data:
          preset_mode: eco
        target:
          entity_id: climate.toon_thermostat
      - service: climate.set_temperature
        data:
          temperature: 5
        target:
          device_id:
            - 59dc73e6760d124ca96a4101045b4bcd
            - d34ef0ce55dbd76e688cea09e359cca8
            - e42629fa9b96f7cde4df1555664810b8
            - 309265144a15110bc63467a83a8759a3
            - 34b54cb00cac76b8e158c5e71abbd5fb
            - 60227a650a897b7ed18df83d4d826556
            - 094695d29b5553dbbbdd9c93ed2059c7
            - f2ecf356f26a33fbecafab2ae1ebecd3
            - d55f1bb2b8d94cc025dac16e2a45be91
      - service: climate.turn_off
        target:
          device_id:
            - 59dc73e6760d124ca96a4101045b4bcd
            - d34ef0ce55dbd76e688cea09e359cca8
            - e42629fa9b96f7cde4df1555664810b8
            - 309265144a15110bc63467a83a8759a3
            - 34b54cb00cac76b8e158c5e71abbd5fb
            - 60227a650a897b7ed18df83d4d826556
            - 094695d29b5553dbbbdd9c93ed2059c7
            - f2ecf356f26a33fbecafab2ae1ebecd3
            - d55f1bb2b8d94cc025dac16e2a45be91
    id: 5b9d4568a9c449258a135702cd0a116a

  - alias: Set Climate to Comfort when back from vacation
    trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 20
    condition:
    - condition: state
      entity_id: group.ouders
      state: not_home
      for: 
        hours: 24
    action:
      - service: climate.set_preset_mode
        data:
          preset_mode: comfort
        target:
          entity_id: climate.toon_thermostat
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 30
        target:
          device_id:
            - 094695d29b5553dbbbdd9c93ed2059c7
            - f2ecf356f26a33fbecafab2ae1ebecd3
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 20
        target:
          device_id:
            - 34b54cb00cac76b8e158c5e71abbd5fb
            - d55f1bb2b8d94cc025dac16e2a45be91
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 19
        target:
          device_id:
            - 60227a650a897b7ed18df83d4d826556
    id: 5b9d4568a9c449258a3a9502cd0a116a


    #================================
    # Radiatoren
    #================================

  - alias: Set Radiator Slaapkamer aan
    trigger:
    - platform: time
      at: '06:10'
    - platform: time
      at: '22:00'
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.toon_thermostat
        attribute: preset_modes
        state: eco
    action:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 16
        target:
          device_id: 309265144a15110bc63467a83a8759a3
    id: 5b9d4568a9c449258a3a95hj81fh5f1

  - alias: Set Radiator Slaapkamer uit
    trigger:
    - platform: time
      at: '08:30'
    - platform: time
      at: '23:30'
    action:
      - service: climate.set_temperature
        data:
          temperature: 5
        target:
          device_id: 309265144a15110bc63467a83a8759a3
    id: 5b9d4568akn6tf258a3a9502cd0a116a

  - alias: Set Radiator Luca en Fynn aan
    trigger:
    - platform: time
      at: '06:10'
    - platform: time
      at: '18:30'
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.toon_thermostat
        attribute: preset_modes
        state: eco
    action:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 16
        target:
          device_id:
            - 59dc73e6760d124ca96a4101045b4bcd
            - e42629fa9b96f7cde4df1555664810b8
    id: 5b9d4568a9c449jks5gv95hj81fh5f1

  - alias: Set Radiator Luca en Fynn uit
    trigger:
    - platform: time
      at: '08:00'
    - platform: time
      at: '20:30'
    action:
      - service: climate.set_temperature
        data:
          temperature: 5
        target:
          device_id:
            - 59dc73e6760d124ca96a4101045b4bcd
            - e42629fa9b96f7cde4df1555664810b8
    id: 5b9ja5dfv6n6tf258a3ahg56200a116a

  - alias: Set Radiator Kantoor aan
    trigger:
    - platform: time
      at: '07:00'
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.toon_thermostat
        attribute: preset_modes
        state: eco
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 20
        target:
          device_id: d34ef0ce55dbd76e688cea09e359cca8
    id: 5b9d45hjna5249258a3a95hj81fh5f1

  - alias: Set Radiator Kantoor uit
    trigger:
    - platform: time
      at: '18:00'
    action:
      - service: climate.set_temperature
        data:
          temperature: 5
        target:
          device_id: d34ef0ce55dbd76e688cea09e359cca8
    id: 5b9d4568akn8kh5dsa3a9502cd0a116a

  - alias: Set Radiator Toilet en Gang aan
    trigger:
    - platform: time
      at: '06:30'
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.toon_thermostat
        attribute: preset_modes
        state: eco
    action:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 20
        target:
          device_id:
            - 34b54cb00cac76b8e158c5e71abbd5fb
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 19
        target:
          device_id:
            - 60227a650a897b7ed18df83d4d826556
    id: 5b9d45hjna5249258a3a95jm75gh5f1

  - alias: Set Radiator Toilet en Gang uit
    trigger:
    - platform: time
      at: '23:00'
    action:
      - service: climate.set_temperature
        data:
          temperature: 5
        target:
          device_id:
            - 60227a650a897b7ed18df83d4d826556
            - 34b54cb00cac76b8e158c5e71abbd5fb
    id: 5b9d4568ah7d3m5dsa3a9502cd0a116a

  - alias: Set Radiator Badkamer aan
    trigger:
    - platform: time
      at: '06:10'
    - platform: time
      at: '18:30'
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.toon_thermostat
        attribute: preset_modes
        state: eco
    action:
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 20
        target:
          device_id: d55f1bb2b8d94cc025dac16e2a45be91
    id: 5b9d4568a9c449ka7gb395hj81fh5f1

  - alias: Set Radiator Badkamer uit
    trigger:
    - platform: time
      at: '09:00'
    - platform: time
      at: '23:30'
    action:
      - service: climate.set_temperature
        data:
          temperature: 5
        target:
          device_id: d55f1bb2b8d94cc025dac16e2a45be91
    id: 5b9dkal097n6tf258a3a9502cd0a116a

    #================================  
    # Batteries
    #================================

  - alias: Replace Radiator Valve Batteries Notification
    trigger:
    - platform: state
      entity_id: binary_sensor.verwarming_badkamer_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_fynn_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_hal_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_keuken_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_luca_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_slaapkamer_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_toilet_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_woonkamer_battery_low
      to: "on"
    - platform: state
      entity_id: binary_sensor.verwarming_zolder_battery_low
      to: "on"
    action:
      service: notify.mobile_app_telefoon_duncan
      data:
        message: >-
            Vervang batterijen van de radiatorknoppen in de volgende kamers:<br>
            {% set x = expand('binary_sensor.verwarming_badkamer_battery_low', 'binary_sensor.verwarming_fynn_battery_low', 'binary_sensor.verwarming_hal_battery_low', 'binary_sensor.verwarming_keuken_battery_low', 'binary_sensor.verwarming_luca_battery_low', 'binary_sensor.verwarming_slaapkamer_battery_low', 'binary_sensor.verwarming_toilet_battery_low', 'binary_sensor.verwarming_woonkamer_battery_low', 'binary_sensor.verwarming_zolder_battery_low') | selectattr('state','eq','on') | map(attribute='object_id') | list %}
            {{ 'none' if x | count == 0 else x | join('<br>') | replace('verwarming_badkamer_battery_low', '- Badkamer') | replace('verwarming_fynn_battery_low', '- Slaapkamer Fynn') | replace('verwarming_hal_battery_low', '- Hal') | replace('verwarming_keuken_battery_low', '- Keuken') | replace('verwarming_luca_battery_low', '- Slaapkamer Luca') | replace('verwarming_slaapkamer_battery_low', '- Slaapkamer') | replace('verwarming_toilet_battery_low', '- Toilet') | replace('verwarming_woonkamer_battery_low', '- Woonkamer') | replace('verwarming_zolder_battery_low', '- Zolder') }}
        data:
          group: radiators
          icon_url: /local/Custom_Icons/battery-empty-ico.png
          ttl: 0
          priority: high
          tag: "replace-radiator-valve-batteries"
    id: 455a2a3la962a7c086c3e626a5f9ae7d



  #===============
  # Sensors
  #===============

sensor:

    #================================
    # Toon smartmeter
    #================================
  - platform: toon_smartmeter
    host: !secret toon_ip
    port: !secret toon_poort
    scan_interval: 10
    resources:
      - gasused
      - gasusedcnt
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
      - elecprodflowlow
      - elecprodcntlow
      - elecprodflowhigh
      - elecprodcnthigh
      - elecsolar
      - elecsolarcnt
      - heat

    #================================
    # Toon boilerstatus
    #================================
  - platform: toon_boilerstatus
    host: !secret toon_ip
    port: !secret toon_poort
    scan_interval: 10
    resources:
      - boilersetpoint
      - boilerintemp
      - boilerouttemp
      - boilerpressure
      - boilermodulationlevel
      - roomtemp
      - roomtempsetpoint

    #================================
    # Gas en Elektra
    #================================ 

  - platform: template
    sensors:
      energy_cost_today:
        friendly_name: 'Energie Kosten Vandaag'
        value_template: "{{ ((states('sensor.dagelijks_energie_verbruik_laag')|float + states('sensor.dagelijks_energie_verbruik_hoog')|float) * ( states('input_number.energy_cost')|float) + states('input_number.energy_cost_daily')|float )|round(2)}}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      gas_cost_today:
        friendly_name: 'Gas Kosten Vandaag'
        value_template: "{{ (states('sensor.dagelijks_gas_verbruik')|float * states('input_number.gas_cost')|float + states('input_number.gas_cost_daily')|float)|round(2) }}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      total_cost_today:
        friendly_name: 'Totale Kosten Vandaag'
        value_template: "{{ (states('sensor.energy_cost_today')|float + states('sensor.gas_cost_today')|float )|round(2) }}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      energy_cost_this_month:
        friendly_name: 'Energie Kosten Deze Maand'
        value_template: "{{ (((states('sensor.maandelijks_energie_verbruik_laag')|float + states('sensor.maandelijks_energie_verbruik_hoog')|float) * ( states('input_number.energy_cost')|float)) + ((states('input_number.energy_cost_daily')|float) * (states('sensor.days_this_month')|float)) )|round(2)}}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      energy_cost_this_year:
        friendly_name: 'Energie Kosten Dit Jaar'
        value_template: "{{ (((states('sensor.jaarlijks_energie_verbruik_laag')|float + states('sensor.jaarlijks_energie_verbruik_hoog')|float) * ( states('input_number.energy_cost')|float)) + ((states('input_number.energy_cost_daily')|float) * (states('sensor.days_this_year')|float)) )|round(2)}}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      gas_cost_this_month:
        friendly_name: 'Gas Kosten Deze Maand'
        value_template: "{{ ((states('sensor.maandelijks_gas_verbruik')|float ) * ( states('input_number.gas_cost')|float) + (states('input_number.gas_cost_daily')|float) * (states('sensor.days_this_month')|float) )|round(2)}}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      total_cost_this_month:
        friendly_name: 'Totale Kosten Deze Maand'
        value_template: "{{ (states('sensor.energy_cost_this_month')|float + states('sensor.gas_cost_this_month')|float )|round(2) }}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      power_usage:
        friendly_name: 'Energie Gebruik'
        value_template: "{{ (states('sensor.toon_p1_power_use_high')|float + states('sensor.toon_p1_power_use_low')|float )|round(2) }}"
        unit_of_measurement: "W"
        icon_template: mdi:flash-outline

  - platform: template
    sensors:
      total_energy_this_month:
        friendly_name: 'Energie Verbruik Deze Maand'
        value_template: "{{ (states('sensor.maandelijks_energie_verbruik_laag')|float + states('sensor.maandelijks_energie_verbruik_hoog')|float )|round(2) }}"
        unit_of_measurement: "kWh"
        icon_template: mdi:flash-outline

  - platform: template
    sensors:
      total_energy_this_year:
        friendly_name: 'Energie Verbruik Dit Jaar'
        value_template: "{{ (states('sensor.jaarlijks_energie_verbruik_laag')|float + states('sensor.jaarlijks_energie_verbruik_hoog')|float )|round(2) }}"
        unit_of_measurement: "kWh"
        icon_template: mdi:flash-outline

    #================================
    # Empty Entities
    #================================

  - platform: template
    sensors:
        kosten:
            friendly_name: Kosten
            icon_template: mdi:currency-eur
            value_template: " "

  - platform: template
    sensors:
        daily_usage:
            friendly_name: Dagelijks Verbruik
            icon_template: mdi:clock-outline
            value_template: " "
            
  - platform: template
    sensors:
        monthly_usage:
            friendly_name: Maandelijks Verbruik
            icon_template: mdi:calendar-month
            value_template: " "