#================================
# Zigbee Map
#================================ 

mqtt:
  sensor:

    - name: Zigbee2mqtt Networkmap
      # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
      state_topic: zigbee2mqtt/bridge/response/networkmap
      value_template: >-
        {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
      json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      json_attributes_template: "{{ value_json.data.value | tojson }}"


  #============
  # Automations
  #============

automation:

  - alias: Update Ikea Tradfri Button Lamp Hoekje
    description: ''
    mode: single
    trigger:
      - platform: state
        entity_id: update.switch_lamp_hoekje
        to: 'on'
    action:
      - service: update.install
        target:
          entity_id:
            - update.switch_lamp_hoekje
    id: 5795jk84ah61k3258a3a9502cd0a116a