#================================
# Crypto
#================================ 

  #================================
  # Sensors
  #================================ 
  
sensor:
  - platform: template
    sensors:
      value_ankr:
        friendly_name: 'Value ANKR'
        value_template: "{{ state_attr('sensor.coinbase_ankr_portemonnee', 'Balance in native currency')|replace(' EUR','') }}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      value_atom:
        friendly_name: 'Value ATOM'
        value_template: "{{ state_attr('sensor.coinbase_staked_atom', 'Balance in native currency')|replace(' EUR','') }}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      value_doge:
        friendly_name: 'Value Doge'
        value_template: "{{ state_attr('sensor.coinbase_doge_wallet', 'Balance in native currency')|replace(' EUR','') }}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur

  - platform: template
    sensors:
      value_xrp:
        friendly_name: 'Value Ripple'
        value_template: "{{ state_attr('sensor.coinbase_xrp_wallet', 'Balance in native currency')|replace(' EUR','') }}"
        unit_of_measurement: "€"
        icon_template: mdi:currency-eur