#================================  
# Hele huis
#================================

- alias: Turn off alle Lampen savonds
  trigger:
  - platform: state
    entity_id: binary_sensor.telefoon_duncan_is_charging
    to: 'on'
    for:
      minutes: 5
  - platform: state
    entity_id: binary_sensor.telefoon_sabrine_is_aan_het_opladen
    to: 'on'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: light.lampen_woonkamer
      state: 'on'
    - condition: state 
      entity_id: binary_sensor.telefoon_duncan_is_charging
      state: 'on'
      for:
        minutes: 5
    - condition: state
      entity_id: binary_sensor.telefoon_sabrine_is_aan_het_opladen
      state: 'on'
      for:
        minutes: 5
    - condition: time
      after: '22:30:00'
      before: '05:00:00'
  action:
  - service: light.turn_off
    entity_id: light.lampen_woonkamer
  - service: light.turn_off
    entity_id: light.lampjes_veranda
  id: 110c40loj06e4a8e8ad9e29092c7d334

- alias: Vakantiemode aan
  trigger:
  - platform: state
    entity_id: climate.toon_thermostat
    attribute: preset_mode
    to: eco
    from: comfort
  action:
  - service: switch.turn_off
    entity_id: switch.shelly_shplg_s_9a53ab
  - service: automation.turn_off
    target:
        entity_id:
          - automation.turn_off_lampen_woonkamer_at_23_30
          - automation.turn_off_lampen_woonkamer_sochtends
          - automation.turn_on_lampen_woonkamer_at_sunset
          - automation.turn_on_lampen_woonkamer_in_the_morning
          - automation.turn_on_lampjes_veranda_at_sunset
          - automation.vacuum_kitchen_and_living
          - automation.radio_aan_sochtends
#  - service: switch.turn_on
#    target:
#      entity_id: switch.presence_simulation
  id: f8a0c07e00a24377b78773bab12dd157

- alias: Vakantiemode uit
  trigger:
  - platform: state
    entity_id: climate.toon_thermostat
    attribute: preset_mode
    from: eco
    to: comfort
  action:
  - service: switch.turn_on
    entity_id: switch.shelly_shplg_s_9a53ab
  - service: automation.turn_on
    target:
      entity_id:
          - automation.turn_off_lampen_woonkamer_at_23_30
          - automation.turn_off_lampen_woonkamer_sochtends
          - automation.turn_on_lampen_woonkamer_at_sunset
          - automation.turn_on_lampen_woonkamer_in_the_morning
          - automation.turn_on_lampjes_veranda_at_sunset
          - automation.vacuum_kitchen_and_living
          - automation.radio_aan_sochtends
#  - service: switch.turn_off
#    target:
#      entity_id: switch.presence_simulation
  id: 5f450d9467d244c597dd1645f33f358c

#================================  
# Lampjes Veranda
#================================

- alias: Turn on Lampjes Veranda at sunset
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
  - platform: state
    entity_id: group.ouders
    from: 'not_home'
    to: 'home'
  condition:
  - condition: template
    value_template: '{{ now().month >= 4 and now().month <= 10 }}'
  - condition: sun
    after: sunset
    after_offset: -00:15:00
  - condition: or
    conditions:
    - condition: state
      entity_id: person.duncan
      state: 'home'
    - condition: state
      entity_id: person.sabrine
      state: 'home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
  action:
    service: light.turn_on
    entity_id: light.lampjes_veranda
  id: 5b9dad4da9c449258a3a9502cd0a116a

#================================  
# Lampen woonkamer
#================================

- alias: Turn on Lampen Woonkamer at sunset
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
  - platform: state
    entity_id: group.ouders
    from: 'not_home'
    to: 'home'
  condition:
  - condition: sun
    after: sunset
    after_offset: -00:15:00
  - condition: or
    conditions:
    - condition: state
      entity_id: person.duncan
      state: 'home'
    - condition: state
      entity_id: person.sabrine
      state: 'home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
  action:
    service: light.turn_on
    entity_id: light.lampen_woonkamer
    data:
      brightness: 28
  id: 5b9dad4d6h8g49258a3a9502cd0a116a

- alias: Turn on Lamp Bank at sunset when not home
  trigger:
  - platform: sun
    event: sunset
    offset: -00:15:00
  condition:
  - condition: sun
    after: sunset
    after_offset: -00:15:00
  - condition: state
    entity_id: person.duncan
    state: 'not_home'
  - condition: state
    entity_id: person.sabrine
    state: 'not_home'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
    service: light.turn_on
    entity_id: light.lamp_bank_hoek
    data:
      brightness: 28
  id: 5b9dad4d6hjk95258a3a9502cd0a116a

- alias: Turn off lights after sunset when leaving home
  trigger:
  - platform: state
    entity_id: group.ouders
    from: 'home'
    to: 'not_home'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: sun
    after: sunset
    after_offset: -00:15:00
  - condition: state
    entity_id: person.duncan
    state: 'not_home'
  - condition: state
    entity_id: person.sabrine
    state: 'not_home'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.lamp_achterdeur
        - light.lamp_haard
        - light.lamp_trap
  id: 5b9dad4d6hjk95258h679502cd0a116a


- alias: Turn off Lampen Woonkamer sochtends
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:15:00
  condition:
    - condition: state
      entity_id: light.lampen_woonkamer
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.woonkamer_lampen
  id: 110c40loj06e4a8u8t59e29092c7d334

- alias: Turn on Lamp Bank Hoek in the morning
  trigger:
  - platform: state
    entity_id: binary_sensor.telefoon_duncan_is_charging
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.telefoon_sabrine_is_aan_het_opladen
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: group.ouders
    from: 'not_home'
    to: 'home'
  condition:
  - condition: sun
    before: sunrise
    after_offset: 00:15:00
  - condition: or
    conditions:
    - condition: state
      entity_id: person.duncan
      state: 'home'
    - condition: state
      entity_id: person.sabrine
      state: 'home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
  action:
    service: light.turn_on
    entity_id: light.lamp_bank_hoek
    data:
      brightness: 28
  id: 5b9dad4d6h8g4925hgb79502cd0a116a

- alias: Turn on Lampen Woonkamer for Romance
  trigger:
  - platform: state
    entity_id: input_boolean.romantic_scene
    to: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.romantic
  id: 5b9dad4d6h8g49258a3a9502cdhnv58k

#================================  
# Lampen slaapkamer Fynn
#================================

- alias: Bediening lamp hoekje - Switch
  description: 'Bediening Lamp hoekje in Slaapkamer Fynn'
  use_blueprint:
    path: EPMatt/ikea_e1743.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.switch_lamp_hoekje_action
      helper_last_controller_event: input_text.lamp_hoekje_helper
      button_up_long_loop: true
      button_down_long_loop: true
      action_button_up_short:
        - device_id: 558b0935bd70be482881308623a794c2
          domain: select
          entity_id: select.lamp_hoekje_power_on_behavior
          type: select_option
          option: 'on'
      action_button_up_long:
        - device_id: 558b0935bd70be482881308623a794c2
          domain: light
          entity_id: light.lamp_hoekje
          type: brightness_increase
      action_button_down_short:
        - device_id: 558b0935bd70be482881308623a794c2
          domain: select
          entity_id: select.lamp_hoekje_power_on_behavior
          type: select_option
          option: 'off'
      action_button_down_long:
        - device_id: 558b0935bd70be482881308623a794c2
          domain: light
          entity_id: light.lamp_hoekje
          type: brightness_decrease
  id: 5jk87d4d6h8g4925hgb79502cd0a116a

- alias: Bediening lamp hoekje - Light
  description: 'Bediening Lamp hoekje in Slaapkamer Fynn'
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      light_color_mode: Auto
      controller_device: a26d39aa1232a5d8c04e912686456714
      controller_entity: sensor.switch_lamp_hoekje_action
      controller_model: IKEA E1743 TRÅDFRI On/Off Switch & Dimmer
      light: light.lamp_hoekje

#================================  
# Addons
#================================

  #================================  
  # Samba Backup
  #================================

- alias: Restore Samba Backup sensor on startup
  trigger:
  - event: start
    platform: homeassistant
  action:
  - service: hassio.addon_restart
    data:
      addon: 15d21743_samba_backup
  id: ba754efce6f94fc19d2947a7eb127fea

  #================================  
  # Updates
  #================================

- alias: Addons have updates
  trigger:
  - platform: state
    entity_id: binary_sensor.updater_addons
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Addons have updates
      message: Updates available for {{ states('sensor.supervisor_updates') }} HA
        addon{% if states('sensor.supervisor_updates') | int > 1 %}s{% endif %}
      data:
        group: updates
        icon_url: /local/Custom_Icons/addons-ico.png
        clickAction: /hassio/dashboard
  id: 32d6b6ff7ffd42e5b4d3374d8bddef70

#================================  
# Home Assistant
#================================

  #================================  
  # Auto Purge DB
  #================================

- alias: Purge Database
  initial_state: True
  trigger:
    platform: time
    at: '04:12:00'
  action:
    service: recorder.purge
    data:
      keep_days: 30
      repack: true
  id: 32d6b6ff7ffd42hya4d3374d8bddef70

  #================================  
  # Theme Switcher
  #================================

- alias: Theme Switcher at Sunset and Sunrise
  trigger:
  - platform: state
    entity_id: sun.sun
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: above_horizon
      sequence:
      - service: frontend.set_theme
        data:
          name: bloom-theme-light
      - service: input_number.set_value
        target:
          entity_id: input_number.nighttime
        data:
          value: 0
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      sequence:
      - service: frontend.set_theme
        data:
          name: bloom-theme-dark
      - service: input_number.set_value
        target:
          entity_id: input_number.nighttime
        data:
          value: 1
  id: f361a4ce325047d2bfb38b5bf46a4077

  #================================  
  # Update template sensors
  #================================

- alias: System - Update Template Sensors
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: /25
  action:
  - service: homeassistant.update_entity
    entity_id:
    - sensor.total_automations
    - sensor.total_binary_sensors
    - sensor.total_cameras
    - sensor.total_counters
    - sensor.total_devicetrackers
    - sensor.total_entities
    - sensor.total_groups
    - sensor.total_input_booleans
    - sensor.total_input_datetimes
    - sensor.total_input_numbers
    - sensor.total_input_selects
    - sensor.total_input_texts
    - sensor.total_lights
    - sensor.total_media_players
    - sensor.total_persons
    - sensor.total_remotes
    - sensor.total_scenes
    - sensor.total_scripts
    - sensor.total_sensors
    - sensor.total_switches
    - sensor.total_timers
    - sensor.total_zones
    - sensor.total_tasmota_devices
    - sensor.domains_in_use
    - sensor.total_shelly_devices
    - sensor.outdated_shelly_devices
  id: 3fe07bd3a8a4424ebf5395df92b65b00

  #================================  
  # Updates
  #================================

- alias: HA has an update
  trigger:
  - platform: state
    entity_id: sensor.updater_core
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for HA available
      message: '{{ state_attr(''sensor.updater_core'', ''current_version'') }} ==>
        {{ state_attr(''sensor.updater_core'', ''newest_version'') }}'
      data:
        group: updates
        icon_url: /local/Pictures/addons/ha-logo.png
        clickAction: /hassio/config/dashboard
  id: fb2e6e01da51489faa8bee310353b4f0

- alias: HassOS has an update
  trigger:
  - platform: state
    entity_id: sensor.hassos_updates
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for HassOS available
      message: '{{ states.sensor.home_assistant_operating_system_version.state }} ==>
        {{ states.sensor.home_assistant_operating_system_newest_version.state }}'
      data:
        group: updates
        icon_url: /local/Pictures/addons/ha-logo.png
        clickAction: /hassio/config/dashboard
  id: c54768ea8c124070bb24724250943d38

- alias: Supervisor has an update
  trigger:
  - platform: state
    entity_id: binary_sensor.updater_supervisor
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for Supervisor available
      message: '{{ state_attr(''sensor.supervisor_updates'', ''current_version'')
        }} ==> {{ state_attr(''sensor.supervisor_updates'', ''newest_version'') }}'
      data:
        group: updates
        icon_url: /local/Pictures/addons/ha-logo.png
        clickAction: /hassio/config/dashboard
  id: df11340c84784621a4e90ad21399a25e

- alias: Audio has an update
  trigger:
  - platform: state
    entity_id: sensor.updater_audio
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for Audio available
      message: '{{ state_attr(''sensor.updater_audio'', ''current_version'') }} ==>
        {{ state_attr(''sensor.updater_audio'', ''newest_version'') }}'
      data:
        group: updates
        icon_url: /local/Custom_Icons/audio-ico.png
        clickAction: /hassio/config/dashboard
  id: b33a2c9993834587a8390adb6d75c09e

- alias: DNS has an update
  trigger:
  - platform: state
    entity_id: sensor.updater_dns
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for DNS available
      message: '{{ state_attr(''sensor.updater_dns'', ''current_version'') }} ==>
        {{ state_attr(''sensor.updater_dns'', ''newest_version'') }}'
      data:
        group: updates
        icon_url: /local/Custom_Icons/dns-ico.png
        clickAction: /hassio/config/dashboard
  id: 06cb6eea2b9e433b845b38f2ba18fea4

- alias: CLI has an update
  trigger:
  - platform: state
    entity_id: sensor.updater_dns
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for CLI available
      message: '{{ state_attr(''sensor.updater_cli'', ''current_version'') }} ==>
        {{ state_attr(''sensor.updater_cli'', ''newest_version'') }}'
      data:
        group: updates
        icon_url: /local/Custom_Icons/cli-ico.png
        clickAction: /hassio/config/dashboard
  id: fc668c66c20f4784a731d29e52bf668d

- alias: Multicast has an update
  trigger:
  - platform: state
    entity_id: sensor.updater_multicast
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for Multicast available
      message: '{{ state_attr(''sensor.updater_multicast'', ''current_version'') }}
        ==> {{ state_attr(''sensor.updater_multicast'', ''newest_version'') }}'
      data:
        group: updates
        icon_url: /local/Custom_Icons/multicast-ico.png
        clickAction: /hassio/config/dashboard
  id: b6f34148791b48c5895239e107e54ba9

- alias: Observer has an update
  trigger:
  - platform: state
    entity_id: sensor.updater_observer
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: Update for Observer available
      message: '{{ state_attr(''sensor.updater_observer'', ''current_version'') }}
        ==> {{ state_attr(''sensor.updater_observer'', ''newest_version'') }}'
      data:
        group: updates
        icon_url: /local/Custom_Icons/observer-ico.png
        clickAction: /hassio/config/dashboard
  id: 039cbb4281124426b682aa5283b6e3b6

- alias: HACS has updates
  trigger:
  - platform: state
    entity_id: binary_sensor.updater_hacs
    to: 'on'
  action:
    service: notify.mobile_app_telefoon_duncan
    data:
      title: HACS has updates
      message: '{% for repo in states.sensor.hacs.attributes.repositories %} {{repo.display_name
        }} {{ repo[''installed_version''] }} -> {{ repo[''available_version''] }}
        {% endfor %}'
      data:
        subtitle: Updates available in {{ states('sensor.hacs') }} HACS repo{% if
          states('sensor.hacs') | int > 1 %}s{% endif %}
        group: updates
        icon_url: /local/Custom_Icons/HACS-3d-ico.png
        clickAction: /hacs/entry
  id: 724ee89d019740f69e32677db22a24be

#================================  
# Guest Mode Reset
#================================

- alias: Guest Mode Reset
  trigger:
  - platform: time
    at: '05:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.guest_mode
  id: f8a0c07e00a24325b78773bab12dd157

#================================  
# Backup to Github
#================================

- alias: Backup to Github
  description: Backs up config to Github
  mode: single
  trigger:
    - platform: time
      at: '03:03'
  condition: []
  action:
    - service: shell_command.github_backup
  id: f8a0c07e00a15795b78773bab12dd157
  
#================================  
# Daily reboot
#================================
- alias: Daily Reboot
  description: Reboot HA daily to keep it fresh
  trigger:
    - platform: time
      at: "02:00:00"
  action:
    - service: homeassistant.restart
  id: f8a0c07e00a24325b78773bab12dh29f
  
  