  #===============
  # Sensors
  #===============

sensor:

    #================================
    # Wasmachine
    #================================

  - platform: template
    sensors:
        wasmachine_status:
          friendly_name: Wasmachine Status
          value_template: >-
            {% if states('sensor.shelly_shplg_s_9d9823_current_consumption')|float > 7 %}
                Washing
            {% elif states('sensor.shelly_shplg_s_9d9823_current_consumption')|float > 0 %}
                Idle
            {% else %}
                Off
            {%- endif %}

    #================================
    # Droger
    #================================

  - platform: template
    sensors:
        droger_status:
          friendly_name: Droger Status
          value_template: >-
            {% if states('sensor.shelly_shsw_pm_98cdac1f389e_current_consumption')|float > 50 %}
                Drying
            {% elif states('sensor.shelly_shsw_pm_98cdac1f389e_current_consumption')|float > 0 %}
                Idle
            {% else %}
                Off
            {%- endif %}

  #===============
  # Automations
  #===============

automation:

    #================================  
    # Wasmachine
    #================================

  - alias: Notification Wasmachine Klaar
    trigger:
    - platform: state
      entity_id: sensor.wasmachine_status
      from: Washing
      to: Idle
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: group.ouders
      state: 'home'
    actions:
    - action: >
          {% if (is_state('device_tracker.telefoon_duncan_2', 'home')) and (is_state('device_tracker.telefoon_sab', 'home'))  %}
            notify.all_mobile
          {% elif is_state('device_tracker.telefoon_duncan_2', 'home') %}
            notify.mobile_app_telefoon_duncan
          {% elif is_state('device_tracker.telefoon_sab', 'home') %}
            notify.mobile_app_telefoon_sab
          {% endif %}
      data:
          title: De wasmachine is klaar
          message: Wil je de wasmachine uitzetten?
          data:
            group: wasmachine
            icon_url: /local/Custom_Icons/wasmachine-ico.png
            ttl: 0
            priority: high
    - action: chime_tts.say
      metadata: {}
      data:
        chime_path: /config/www/Custom_Sounds/Chime.mp3
        message: Goedendag, de wasmachine is klaar.
        volume_level: 0.5
        announce: true
      target:
        device_id:
          - 407814b5fab7b9f31d26b2c6370131f5
          - 7cf1501464637063c40475ab9e34a8e9     
    id: 69f61c8b6bd1447aa49592ef3d50f831

    #================================  
    # Droger
    #================================

  - alias: Notification Droger Klaar
    trigger:
    - platform: state
      entity_id: sensor.droger_status
      from: Drying
      to: Idle
      for:
        minutes: 2
    condition:
    - condition: state
      entity_id: group.ouders
      state: 'home'
      # Don't send this alert if it was last triggered less than 30 minutes ago (1,800 seconds)
    - condition: template
      value_template: >
          {% if states.automation.notification_droger_klaar.last_triggered is not none %}
            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.notification_droger_klaar.attributes.last_triggered) | int > 3600 %} true {% else %} false
            {% endif %}
          {% else %}
          false
          {% endif %}
    actions:
    - action: >
        {% if (is_state('device_tracker.telefoon_duncan_2', 'home')) and (is_state('device_tracker.telefoon_sab', 'home'))  %}
          notify.all_mobile
        {% elif is_state('device_tracker.telefoon_duncan_2', 'home') %}
          notify.mobile_app_telefoon_duncan
        {% elif is_state('device_tracker.telefoon_sab', 'home') %}
          notify.mobile_app_telefoon_sab
        {% endif %}
      data:
        title: De droger is klaar
        message: Wil je de droger uitzetten?
        data:
          group: droger
          icon_url: /local/Custom_Icons/droger-ico.png
          ttl: 0
          priority: high
    - action: chime_tts.say
      metadata: {}
      data:
        chime_path: /config/www/Custom_Sounds/Chime.mp3
        message: Goedendag, de droger is klaar.
        volume_level: 0.5
        announce: true
      target:
        device_id:
          - 407814b5fab7b9f31d26b2c6370131f5
          - 7cf1501464637063c40475ab9e34a8e9   
    id: 69f61c8b6k86g47aa49592ef3d50f831