#================================
# Shelly
#================================

shelly:
  discovery: true  #add all devices (default)
  username: !secret shelly_user
  password: !secret shelly_password
  sensors:
      - all #show all sensors
  devices:
      - id: "40F52000C449"
        name: Lamp Tuinkast
        light_switch: true
      - id: "9a5381"
        name: CV
      - id: "9d9823"
        name: Wasmachine
      - id: "9a53ab"
        name: Boiler
      - id: "40F520009959"
        name: Spotjes Dakkapel
        light_switch: true
      - id: "98CDAC1F389E"
        name: Droger

  #================================
  # Automations
  #================================

automation:

    #================================
    # Update Shelly Firmware
    #================================

  - alias: Update Shelly Firmware
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.shelly_shsw_1_40f52000c449_firmware_update
          - switch.shelly_shplg_s_9d9823_firmware_update
          - switch.shelly_shplg_s_9a53ab_firmware_update                    
          - switch.shelly_shplg_s_9a5381_firmware_update
          - switch.shelly_shsw_pm_98cdac1f389e_firmware_update
          - switch.shelly_shsw_1_40f520009959_firmware_update
        to: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.shelly_shsw_1_40f52000c449_firmware_update
            - switch.shelly_shplg_s_9d9823_firmware_update            
            - switch.shelly_shplg_s_9a53ab_firmware_update
            - switch.shelly_shplg_s_9a5381_firmware_update
            - switch.shelly_shsw_pm_98cdac1f389e_firmware_update
            - switch.shelly_shsw_1_40f520009959_firmware_update